### ISSUE TITLE
expect_or_quarantine

### ISSUE THREAD

**Issue by thbeh** [databrickslabs/dlt-meta#1]
Hi, not an error  but I was looking at this and noticed you defined

   _"expect_or_quarantine":{
     "valid_operation":"operation IN ('APPEND', 'DELETE', 'UPDATE')"
   }_
in one of the dqe. But when I tried, it throws

_AttributeError: module 'dlt' has no attribute 'expect_or_quarantine',Map(),Map(),List(),List(),Map())_ 

Is there something I missed?

**Comment by ravi-databricks** [comment]
are you using expect_or_quarantine using dlt API or using dlt-meta framework? There no in built api provided by DLT, DLT-META uses this json rule to produce separate table using  `dlt.expect_all_or_drop(expect_or_quarantine_dict)` [https://github.com/databricks/dlt-meta/blob/main/src/dataflow_pipeline.py#LL204C37-L204C37](url)

**Comment by thbeh** [comment]
Oh...no worries. I thought it was a DLT feature. Nice work for dlt-meta.
