### ISSUE TITLE
java.lang.RuntimeException: non-nullable field authBytes was serialized as null

### ISSUE THREAD

**Issue by msdotnetclr** [databrickslabs/dlt-meta#13]
With Event Hubs source configuration like the following:

      "source_format": "eventhub",
      "source_details": {
         "source_schema_path": "{dbfs_path}/integration-tests/resources/eventhub_iot_schema.ddl",
         "eventhub.accessKeyName": "{eventhub_accesskey_name}",
         "eventhub.name": "{eventhub_name}",
         "eventhub.secretsScopeName": "{eventhub_secrets_scope_name}",
         "kafka.sasl.mechanism": "PLAIN",
         "kafka.security.protocol": "SASL_SSL",
         "eventhub.namespace": "{eventhub_nmspace}",
         "eventhub.port": "{eventhub_port}"
      },

The pipeline may fail with the following error:

Connection to node -1 ({eventhub_nmspace}.servicebus.windows.net/xx.xx.xx.xx:9093) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
...
Unexpected error from {eventhub_nmspace}.servicebus.windows.net/xx.xx.xx.xx (channelId=-1); closing connection
java.lang.RuntimeException: non-nullable field authBytes was serialized as null

**Comment by msdotnetclr** [comment]
I believe the problem is in src/pipeline_readers.py, function PipelineReaders.get_eventhub_kafka_options().

Essentially, when eh_shared_key_value is constructed, The "eh_shared_key_name" in f-string "SharedAccessKeyName={eh_shared_key_name};SharedAccessKey={eh_shared_key_value}" is supposed to be the name of the Shared Access Policy, not the value retrieved from "eventhub.accessKeyName" which holds the name of the secret holding the actual Shared Access Policy value. It will work if the name of the secret is exactly the same as the name of the Shared Access Policy, but if the two names are different, authentication will fail due to invalid SharedAccessKeyName value in the connection string.

I propose to introduce a new source_details option "eventhub.accessKeySecretName" to store the name of the secret, keep "eventhub.accessKeyName" to store the actual Shared Access Policy name, and use both to construct eh_shared_key_value correctly.

**Comment by ravi-databricks** [comment]
Merged fix in v.0.04 release
