### ISSUE TITLE
Support combining Bronze and Silver Spec in one DLT pipeline

### ISSUE THREAD

**Issue by sathya-reddy-m** [databrickslabs/dlt-meta#24]

**Comment by ravi-databricks** [comment]
There is one active [PR](https://github.com/databrickslabs/dlt-meta/pull/8). We can look into this in coming quarter.

**Comment by ravi-databricks** [comment]
Closing this issue since there is new similar [Issue](https://github.com/databrickslabs/dlt-meta/issues/94) which is implemented using dlt **direct publishing mode**
