### ISSUE TITLE
Unity dataflowspec tables

### ISSUE THREAD

**Issue by Vosec** [databrickslabs/dlt-meta#3]
Hello,

if the dataflowspecs tables + bronze/silver tables are stored in schema managed by UC, what is the reason to use/set paths for these tables?
I'm unable to create dataflowspec tables if I want them to be stored in schema managed by UC. If I store it in hive_metastore, it runs fine.

The main issue is that users don't know the paths for the tables managed by UC, they should only reference the tables names in specific schema. Or am I missing something?

"silver_dataflowspec_table": "silver_dataflowspec_table",
"silver_dataflowspec_path": "dbfs:/onboarding_tables_cdc/silver",
 "bronze_dataflowspec_table": "bronze_dataflowspec_table",
 "bronze_dataflowspec_path": "dbfs:/onboarding_tables_cdc/bronze",

Thanks.

**Comment by ravi-databricks** [comment]
@Vosec dlt-meta does not support UC, we will be making new release for UC support.

**Comment by doxie-king** [comment]
What's the timeline on this getting added with support for UC?

**Comment by ravi-databricks** [comment]
AS of now there is working branch for [UC support] (https://github.com/databrickslabs/dlt-meta/tree/feature/dlt-meta-uc). we will plan to release UC branch in coming quarter.

**Comment by ravi-databricks** [comment]
Just update on UC feature: There is [PR#28](https://github.com/databrickslabs/dlt-meta/pull/28) which will be merged soon to main.

**Comment by ravi-databricks** [comment]
UC Support is released to main branch
