### ISSUE TITLE
Silver Transformations Became a Dependency

### ISSUE THREAD

**Issue by nathan-lammers** [databrickslabs/dlt-meta#42]
`TypeError: __init__() missing 1 required positional argument: 'dataQualityExpectations',None,Map(),Map(),List(),List(),Map())`

When a Delta Live Table is onboarded thru a previous version of DLT-META without silver data quality expectations, the code will fail when invoking the [launch notebook](https://databrickslabs.github.io/dlt-meta/getting_started/dltpipelineopt2/).

**Comment by ravi-databricks** [comment]
One solution to this issue would be re-create onboarding tables since schema has changed. we added silver_data_quality_rules column to silver dataflowspec table.

**Comment by nathan-lammers** [comment]
Thanks Ravi!

Cheers,

Nathan Lammers
[Image]
***@***.******@***.***>
(714) 916-4649

From: Ravi Gawai ***@***.***>
Date: Monday, April 15, 2024 at 9:41 AM
To: databrickslabs/dlt-meta ***@***.***>
Cc: Nathan Lammers ***@***.***>, Author ***@***.***>
Subject: Re: [databrickslabs/dlt-meta] Silver Transformations Became a Dependency (Issue #42)
One solution to this issue would be re-create onboarding tables since schema has changed. we added silver_data_quality_rules column to silver dataflowspec table. — Reply to this email directly, view it on GitHub, or unsubscribe. You are


One solution to this issue would be re-create onboarding tables since schema has changed. we added silver_data_quality_rules column to silver dataflowspec table.
