### ISSUE TITLE
It appears that schema ddl is being required when using cdc_apply_changes

### ISSUE THREAD

**Issue by mweirath** [databrickslabs/dlt-meta#90]
I am trying to use cdc_apply_changes with a bronze table that we are using schema evolution (so no defined schema).  Having a schema isn't required by Databricks for this operation, but it appears that the code is checking for a schema ddl before you can run use cdc_apply_changes.

**Comment by ravi-databricks** [comment]
@mweirath see if [this](https://github.com/databrickslabs/dlt-meta/tree/issue_90) fix resolves it! 
If you are using autoloader you dont need to provide schema ddl and apply_changes would work for evolving schema.

**Comment by mweirath** [comment]
Thanks I will work on getting this version pulled in and tested tomorrow.

**Comment by mweirath** [comment]
@ravi-databricks - I confirmed with my team that we were able to pull in the change, and everything appears to be working now.  Thank you for the quick fix.  I will keep an eye out for v0.9 to come out.

I'm not sure if you close these or me.

**Comment by ravi-databricks** [comment]
@mweirath you can close it with comments! thanks!

**Comment by mweirath** [comment]
Confirmed fixed, thank you.
